# Site settings
title: CrimeScienceMX
email: prestevez@crimescience
description: > # this means to ignore newlines until "baseurl:"
  Un blog sobre *Crime Science* en español.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://crimescience.mx" # the base hostname & protocol for your site
twitter_username: CrimeScienceMX
github_username:  

# Build settings
markdown: kramdown
